require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

# Firebase needs this flag to play nicely with React Native
$RNFirebaseAsStaticFramework = true

target 'ZoomConnect' do
  # Ye line Firebase (Swift) ke liye MUST hai, iske bina -Swift.h header nahi banega
  use_frameworks! :linkage => :static

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # React Native's script will handle the rest of the New Arch flags natively
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end